import os 

# os.system(f'CUDA_VISIBLE_DEVICES=0 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f0.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/cf1_cls1_f0')
# os.system(f'CUDA_VISIBLE_DEVICES=0 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f1.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/cf1_cls1_f1')
# os.system(f'CUDA_VISIBLE_DEVICES=0 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f2.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/cf1_cls1_f2')
# os.system(f'CUDA_VISIBLE_DEVICES=0 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f3.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/cf1_cls1_f3')
# os.system(f'CUDA_VISIBLE_DEVICES=0 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f4.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/cf1_cls1_f4')

# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f0.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/cf1_cls1_m_f0')
# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f1.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/cf1_cls1_m_f1')
# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f2.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/cf1_cls1_m_f2')
# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f3.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/cf1_cls1_m_f3')
# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f4.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/cf1_cls1_m_f4')

# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f0.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/cf1_cls1_l_f0')
# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f1.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/cf1_cls1_l_f1')
# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f2.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/cf1_cls1_l_f2')
# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f3.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/cf1_cls1_l_f3')
# os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 640 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f4.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/cf1_cls1_l_f4')

os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f0.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f0')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f1.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f1')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f2.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f2')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f3.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f3')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f4.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f4')

os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f0.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/384cf1_cls1_f0')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f1.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/384cf1_cls1_f1')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f2.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/384cf1_cls1_f2')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f3.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/384cf1_cls1_f3')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f4.yaml --cfg ../yolov5/models/yolov5s_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5s.pt --project runs/384cf1_cls1_f4')

os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f0.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/384cf1_cls1_m_f0')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f1.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/384cf1_cls1_m_f1')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f2.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/384cf1_cls1_m_f2')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f3.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/384cf1_cls1_m_f3')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f4.yaml --cfg ../yolov5/models/yolov5m_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5m.pt --project runs/384cf1_cls1_m_f4')

os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f0.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/384cf1_cls1_l_f0')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f1.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/384cf1_cls1_l_f1')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f2.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/384cf1_cls1_l_f2')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f3.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/384cf1_cls1_l_f3')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f4.yaml --cfg ../yolov5/models/yolov5l_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5l.pt --project runs/384cf1_cls1_l_f4')

os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f0.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f0')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f1.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f1')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f2.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f2')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f3.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f3')
os.system(f'CUDA_VISIBLE_DEVICES=1 python train.py --img-size 384 --epochs 50 --batch-size 8 --data ../yolov5/data/cf1_cls1_f4.yaml --cfg ../yolov5/models/yolov5x_1cls.yaml --weights ../../../../yolov5/pretrained/yolov5x.pt --project runs/384cf1_cls1_x_f4')
